//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intertazz.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EFIntertazzModelContainer : DbContext
    {
        public EFIntertazzModelContainer()
            : base("name=EFIntertazzModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Marca> MarcaSet { get; set; }
        public virtual DbSet<Facturas> FacturasSet { get; set; }
        public virtual DbSet<Stock> StockSet { get; set; }
        public virtual DbSet<Producto> ProductoSet { get; set; }
        public virtual DbSet<Precio> PrecioSet { get; set; }
        public virtual DbSet<TipoProducto> TipoProductoSet { get; set; }
        public virtual DbSet<Categoria> CategoriaSet { get; set; }
        public virtual DbSet<Inventario> InventarioSet { get; set; }
        public virtual DbSet<DetalleFacturas> DetalleFacturasSet { get; set; }
    }
}
