//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intertazz.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EFIntertazzModelContainer : DbContext
    {
        public EFIntertazzModelContainer()
            : base("name=EFIntertazzModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<Facturas> Facturas { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Precio> Precio { get; set; }
        public virtual DbSet<TipoProducto> TipoProducto { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Inventario> Inventario { get; set; }
        public virtual DbSet<DetalleFacturas> DetalleFacturas { get; set; }
    }
}
