
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Intertazz.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Facturas
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Facturas()
    {

        this.Activo = true;

    }


    public long IdFacturas { get; set; }

    public System.DateTime Fecha { get; set; }

    public double Descuento { get; set; }

    public double ValorTotal { get; set; }

    public bool Activo { get; set; }

}

}
