//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intertazz.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Activo = true;
        }
    
        public int IdProducto { get; set; }
        public string Referencia { get; set; }
        public string Nombre { get; set; }
        public bool Activo { get; set; }
    
        public virtual Marca Marca { get; set; }
        public virtual Categoria Categoria { get; set; }
        public virtual TipoProducto TipoProducto { get; set; }
    }
}
